version: '3.9'

services:
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    build: .
    container_name: market
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    env_file:
      - ./.env.dev
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
       - 6379:6379
  celery:
      restart: always
      build:
        context: .
      command: celery -A marketplace worker -l info --pool=solo
      volumes:
        - .:/usr/src/app
      environment:
        - DB_HOST=db
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASS=postgres
      depends_on:
        - db
        - redis
        - web

volumes:
  postgres_data:
